name : CI

#Évènements
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    name: Build docker image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #Step to install Docker to environment
      - name: Set up Docker Buildx
        uses:  docker/setup-buildx-action@v3

      #login to container registry
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract meta data (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build ans push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}